// GENERATED FILE — do not edit.
// Regenerate with: node scripts/embed-migrations.mjs
//
// The migrations are embedded rather than read from disk so they are guaranteed
// to be present in a serverless bundle.

export type Migration = { name: string; statements: string[] };

export const MIGRATIONS: Migration[] = [
  {
    "name": "0000_great_kat_farrell.sql",
    "statements": [
      "CREATE TYPE \"public\".\"crew_status\" AS ENUM('available', 'working', 'traveling', 'off');",
      "CREATE TYPE \"public\".\"invoice_status\" AS ENUM('draft', 'sent', 'paid', 'overdue', 'void');",
      "CREATE TYPE \"public\".\"job_status\" AS ENUM('unscheduled', 'scheduled', 'in_progress', 'complete', 'cancelled');",
      "CREATE TYPE \"public\".\"lead_source\" AS ENUM('website', 'intake_form', 'phone', 'text', 'email', 'facebook', 'instagram', 'referral', 'google', 'repeat', 'walk_by');",
      "CREATE TYPE \"public\".\"lead_status\" AS ENUM('new', 'contacted', 'quoted', 'won', 'lost', 'archived');",
      "CREATE TYPE \"public\".\"message_channel\" AS ENUM('sms', 'email', 'call', 'note');",
      "CREATE TYPE \"public\".\"message_direction\" AS ENUM('inbound', 'outbound');",
      "CREATE TYPE \"public\".\"payment_method\" AS ENUM('card', 'ach', 'cash', 'check', 'other');",
      "CREATE TYPE \"public\".\"photo_kind\" AS ENUM('before', 'after', 'progress', 'issue', 'lead');",
      "CREATE TYPE \"public\".\"plan_tier\" AS ENUM('starter', 'pro', 'scale');",
      "CREATE TYPE \"public\".\"quote_status\" AS ENUM('draft', 'sent', 'viewed', 'accepted', 'declined', 'expired');",
      "CREATE TYPE \"public\".\"task_status\" AS ENUM('pending', 'sent', 'cancelled', 'failed');",
      "CREATE TYPE \"public\".\"user_role\" AS ENUM('owner', 'admin', 'crew');",
      "CREATE TABLE \"activity_events\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"summary\" text NOT NULL,\n\t\"entity_type\" text,\n\t\"entity_id\" uuid,\n\t\"amount_cents\" integer,\n\t\"actor_user_id\" uuid,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"automations\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"key\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"enabled\" boolean DEFAULT true NOT NULL,\n\t\"steps\" jsonb DEFAULT '[]'::jsonb NOT NULL\n);",
      "CREATE TABLE \"businesses\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"slug\" text NOT NULL,\n\t\"phone\" text,\n\t\"email\" text,\n\t\"address_line\" text,\n\t\"city\" text,\n\t\"state\" text,\n\t\"postal_code\" text,\n\t\"timezone\" text DEFAULT 'America/New_York' NOT NULL,\n\t\"plan\" \"plan_tier\" DEFAULT 'pro' NOT NULL,\n\t\"logo_url\" text,\n\t\"hourly_rate_cents\" integer DEFAULT 7500 NOT NULL,\n\t\"minimum_job_cents\" integer DEFAULT 15000 NOT NULL,\n\t\"material_markup_pct\" real DEFAULT 20 NOT NULL,\n\t\"travel_fee_cents\" integer DEFAULT 0 NOT NULL,\n\t\"tax_rate_pct\" real DEFAULT 0 NOT NULL,\n\t\"working_hours\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"default_job_buffer_min\" integer DEFAULT 30 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"crew_members\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"crew_id\" uuid NOT NULL,\n\t\"user_id\" uuid NOT NULL\n);",
      "CREATE TABLE \"crews\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"color\" text DEFAULT '#2a6746' NOT NULL,\n\t\"status\" \"crew_status\" DEFAULT 'available' NOT NULL,\n\t\"last_lat\" real,\n\t\"last_lng\" real,\n\t\"last_ping_at\" timestamp with time zone,\n\t\"active\" boolean DEFAULT true NOT NULL\n);",
      "CREATE TABLE \"customers\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"email\" text,\n\t\"phone\" text,\n\t\"address_line\" text,\n\t\"city\" text,\n\t\"state\" text,\n\t\"postal_code\" text,\n\t\"lat\" real,\n\t\"lng\" real,\n\t\"notes\" text,\n\t\"tags\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"invoices\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"customer_id\" uuid NOT NULL,\n\t\"job_id\" uuid,\n\t\"number\" integer NOT NULL,\n\t\"public_token\" text NOT NULL,\n\t\"status\" \"invoice_status\" DEFAULT 'draft' NOT NULL,\n\t\"subtotal_cents\" integer DEFAULT 0 NOT NULL,\n\t\"tax_cents\" integer DEFAULT 0 NOT NULL,\n\t\"total_cents\" integer DEFAULT 0 NOT NULL,\n\t\"amount_paid_cents\" integer DEFAULT 0 NOT NULL,\n\t\"due_at\" timestamp with time zone,\n\t\"sent_at\" timestamp with time zone,\n\t\"paid_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"job_checklist_items\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"job_id\" uuid NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"done\" boolean DEFAULT false NOT NULL,\n\t\"done_at\" timestamp with time zone,\n\t\"done_by_user_id\" uuid,\n\t\"sort_order\" integer DEFAULT 0 NOT NULL\n);",
      "CREATE TABLE \"job_photos\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"job_id\" uuid,\n\t\"lead_id\" uuid,\n\t\"kind\" \"photo_kind\" DEFAULT 'before' NOT NULL,\n\t\"url\" text NOT NULL,\n\t\"caption\" text,\n\t\"uploaded_by_user_id\" uuid,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"jobs\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"customer_id\" uuid NOT NULL,\n\t\"quote_id\" uuid,\n\t\"crew_id\" uuid,\n\t\"number\" integer NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"description\" text,\n\t\"status\" \"job_status\" DEFAULT 'unscheduled' NOT NULL,\n\t\"scheduled_start\" timestamp with time zone,\n\t\"scheduled_end\" timestamp with time zone,\n\t\"started_at\" timestamp with time zone,\n\t\"completed_at\" timestamp with time zone,\n\t\"value_cents\" integer DEFAULT 0 NOT NULL,\n\t\"address_line\" text,\n\t\"city\" text,\n\t\"state\" text,\n\t\"postal_code\" text,\n\t\"lat\" real,\n\t\"lng\" real,\n\t\"crew_notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"leads\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"customer_id\" uuid,\n\t\"name\" text NOT NULL,\n\t\"email\" text,\n\t\"phone\" text,\n\t\"address_line\" text,\n\t\"city\" text,\n\t\"state\" text,\n\t\"postal_code\" text,\n\t\"service_id\" uuid,\n\t\"request_text\" text NOT NULL,\n\t\"summary\" text,\n\t\"urgency_score\" integer,\n\t\"preferred_date\" text,\n\t\"preferred_window\" text,\n\t\"source\" \"lead_source\" DEFAULT 'website' NOT NULL,\n\t\"status\" \"lead_status\" DEFAULT 'new' NOT NULL,\n\t\"estimate_low_cents\" integer,\n\t\"estimate_high_cents\" integer,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"messages\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"customer_id\" uuid,\n\t\"job_id\" uuid,\n\t\"quote_id\" uuid,\n\t\"direction\" \"message_direction\" NOT NULL,\n\t\"channel\" \"message_channel\" DEFAULT 'sms' NOT NULL,\n\t\"body\" text NOT NULL,\n\t\"automated\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"payments\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"invoice_id\" uuid NOT NULL,\n\t\"amount_cents\" integer NOT NULL,\n\t\"method\" \"payment_method\" DEFAULT 'card' NOT NULL,\n\t\"provider_ref\" text,\n\t\"provider\" text DEFAULT 'manual' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"quote_items\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"quote_id\" uuid NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"kind\" text DEFAULT 'labor' NOT NULL,\n\t\"quantity\" real DEFAULT 1 NOT NULL,\n\t\"unit_price_cents\" integer DEFAULT 0 NOT NULL,\n\t\"total_cents\" integer DEFAULT 0 NOT NULL,\n\t\"sort_order\" integer DEFAULT 0 NOT NULL\n);",
      "CREATE TABLE \"quotes\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"customer_id\" uuid NOT NULL,\n\t\"lead_id\" uuid,\n\t\"number\" integer NOT NULL,\n\t\"public_token\" text NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"notes\" text,\n\t\"status\" \"quote_status\" DEFAULT 'draft' NOT NULL,\n\t\"subtotal_cents\" integer DEFAULT 0 NOT NULL,\n\t\"tax_cents\" integer DEFAULT 0 NOT NULL,\n\t\"total_cents\" integer DEFAULT 0 NOT NULL,\n\t\"valid_until\" timestamp with time zone,\n\t\"sent_at\" timestamp with time zone,\n\t\"viewed_at\" timestamp with time zone,\n\t\"responded_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"reviews\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"customer_id\" uuid NOT NULL,\n\t\"job_id\" uuid,\n\t\"public_token\" text NOT NULL,\n\t\"rating\" integer,\n\t\"private_feedback\" text,\n\t\"routed_to_public\" boolean DEFAULT false NOT NULL,\n\t\"requested_at\" timestamp with time zone,\n\t\"responded_at\" timestamp with time zone\n);",
      "CREATE TABLE \"scheduled_tasks\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"automation_id\" uuid,\n\t\"automation_key\" text NOT NULL,\n\t\"step_index\" integer DEFAULT 0 NOT NULL,\n\t\"entity_type\" text NOT NULL,\n\t\"entity_id\" uuid NOT NULL,\n\t\"run_at\" timestamp with time zone NOT NULL,\n\t\"status\" \"task_status\" DEFAULT 'pending' NOT NULL,\n\t\"last_error\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"services\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text,\n\t\"base_price_cents\" integer DEFAULT 0 NOT NULL,\n\t\"typical_hours\" real DEFAULT 2 NOT NULL,\n\t\"min_price_cents\" integer,\n\t\"estimate_low_pct\" real DEFAULT 85 NOT NULL,\n\t\"estimate_high_pct\" real DEFAULT 125 NOT NULL,\n\t\"recurring\" boolean DEFAULT false NOT NULL,\n\t\"active\" boolean DEFAULT true NOT NULL,\n\t\"sort_order\" integer DEFAULT 0 NOT NULL\n);",
      "CREATE TABLE \"sessions\" (\n\t\"token\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"users\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"business_id\" uuid NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"password_hash\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"phone\" text,\n\t\"role\" \"user_role\" DEFAULT 'crew' NOT NULL,\n\t\"avatar_color\" text DEFAULT '#2a6746' NOT NULL,\n\t\"active\" boolean DEFAULT true NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "ALTER TABLE \"activity_events\" ADD CONSTRAINT \"activity_events_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"activity_events\" ADD CONSTRAINT \"activity_events_actor_user_id_users_id_fk\" FOREIGN KEY (\"actor_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"automations\" ADD CONSTRAINT \"automations_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"crew_members\" ADD CONSTRAINT \"crew_members_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"crew_members\" ADD CONSTRAINT \"crew_members_crew_id_crews_id_fk\" FOREIGN KEY (\"crew_id\") REFERENCES \"public\".\"crews\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"crew_members\" ADD CONSTRAINT \"crew_members_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"crews\" ADD CONSTRAINT \"crews_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"customers\" ADD CONSTRAINT \"customers_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"invoices\" ADD CONSTRAINT \"invoices_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"invoices\" ADD CONSTRAINT \"invoices_customer_id_customers_id_fk\" FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"invoices\" ADD CONSTRAINT \"invoices_job_id_jobs_id_fk\" FOREIGN KEY (\"job_id\") REFERENCES \"public\".\"jobs\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"job_checklist_items\" ADD CONSTRAINT \"job_checklist_items_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"job_checklist_items\" ADD CONSTRAINT \"job_checklist_items_job_id_jobs_id_fk\" FOREIGN KEY (\"job_id\") REFERENCES \"public\".\"jobs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"job_checklist_items\" ADD CONSTRAINT \"job_checklist_items_done_by_user_id_users_id_fk\" FOREIGN KEY (\"done_by_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"job_photos\" ADD CONSTRAINT \"job_photos_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"job_photos\" ADD CONSTRAINT \"job_photos_job_id_jobs_id_fk\" FOREIGN KEY (\"job_id\") REFERENCES \"public\".\"jobs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"job_photos\" ADD CONSTRAINT \"job_photos_lead_id_leads_id_fk\" FOREIGN KEY (\"lead_id\") REFERENCES \"public\".\"leads\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"job_photos\" ADD CONSTRAINT \"job_photos_uploaded_by_user_id_users_id_fk\" FOREIGN KEY (\"uploaded_by_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"jobs\" ADD CONSTRAINT \"jobs_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"jobs\" ADD CONSTRAINT \"jobs_customer_id_customers_id_fk\" FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"jobs\" ADD CONSTRAINT \"jobs_quote_id_quotes_id_fk\" FOREIGN KEY (\"quote_id\") REFERENCES \"public\".\"quotes\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"jobs\" ADD CONSTRAINT \"jobs_crew_id_crews_id_fk\" FOREIGN KEY (\"crew_id\") REFERENCES \"public\".\"crews\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"leads\" ADD CONSTRAINT \"leads_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"leads\" ADD CONSTRAINT \"leads_customer_id_customers_id_fk\" FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"leads\" ADD CONSTRAINT \"leads_service_id_services_id_fk\" FOREIGN KEY (\"service_id\") REFERENCES \"public\".\"services\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"messages\" ADD CONSTRAINT \"messages_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"messages\" ADD CONSTRAINT \"messages_customer_id_customers_id_fk\" FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"messages\" ADD CONSTRAINT \"messages_job_id_jobs_id_fk\" FOREIGN KEY (\"job_id\") REFERENCES \"public\".\"jobs\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"messages\" ADD CONSTRAINT \"messages_quote_id_quotes_id_fk\" FOREIGN KEY (\"quote_id\") REFERENCES \"public\".\"quotes\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"payments\" ADD CONSTRAINT \"payments_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"payments\" ADD CONSTRAINT \"payments_invoice_id_invoices_id_fk\" FOREIGN KEY (\"invoice_id\") REFERENCES \"public\".\"invoices\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"quote_items\" ADD CONSTRAINT \"quote_items_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"quote_items\" ADD CONSTRAINT \"quote_items_quote_id_quotes_id_fk\" FOREIGN KEY (\"quote_id\") REFERENCES \"public\".\"quotes\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"quotes\" ADD CONSTRAINT \"quotes_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"quotes\" ADD CONSTRAINT \"quotes_customer_id_customers_id_fk\" FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"quotes\" ADD CONSTRAINT \"quotes_lead_id_leads_id_fk\" FOREIGN KEY (\"lead_id\") REFERENCES \"public\".\"leads\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"reviews\" ADD CONSTRAINT \"reviews_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"reviews\" ADD CONSTRAINT \"reviews_customer_id_customers_id_fk\" FOREIGN KEY (\"customer_id\") REFERENCES \"public\".\"customers\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"reviews\" ADD CONSTRAINT \"reviews_job_id_jobs_id_fk\" FOREIGN KEY (\"job_id\") REFERENCES \"public\".\"jobs\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "ALTER TABLE \"scheduled_tasks\" ADD CONSTRAINT \"scheduled_tasks_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"scheduled_tasks\" ADD CONSTRAINT \"scheduled_tasks_automation_id_automations_id_fk\" FOREIGN KEY (\"automation_id\") REFERENCES \"public\".\"automations\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"services\" ADD CONSTRAINT \"services_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "ALTER TABLE \"users\" ADD CONSTRAINT \"users_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "CREATE INDEX \"activity_business_time_idx\" ON \"activity_events\" USING btree (\"business_id\",\"created_at\");",
      "CREATE UNIQUE INDEX \"automations_key_idx\" ON \"automations\" USING btree (\"business_id\",\"key\");",
      "CREATE UNIQUE INDEX \"businesses_slug_idx\" ON \"businesses\" USING btree (\"slug\");",
      "CREATE UNIQUE INDEX \"crew_member_unique\" ON \"crew_members\" USING btree (\"crew_id\",\"user_id\");",
      "CREATE INDEX \"crews_business_idx\" ON \"crews\" USING btree (\"business_id\");",
      "CREATE INDEX \"customers_business_idx\" ON \"customers\" USING btree (\"business_id\");",
      "CREATE INDEX \"customers_name_idx\" ON \"customers\" USING btree (\"name\");",
      "CREATE UNIQUE INDEX \"invoices_token_idx\" ON \"invoices\" USING btree (\"public_token\");",
      "CREATE UNIQUE INDEX \"invoices_number_idx\" ON \"invoices\" USING btree (\"business_id\",\"number\");",
      "CREATE INDEX \"invoices_business_status_idx\" ON \"invoices\" USING btree (\"business_id\",\"status\");",
      "CREATE INDEX \"checklist_job_idx\" ON \"job_checklist_items\" USING btree (\"job_id\");",
      "CREATE INDEX \"photos_job_idx\" ON \"job_photos\" USING btree (\"job_id\");",
      "CREATE INDEX \"photos_lead_idx\" ON \"job_photos\" USING btree (\"lead_id\");",
      "CREATE UNIQUE INDEX \"jobs_number_idx\" ON \"jobs\" USING btree (\"business_id\",\"number\");",
      "CREATE INDEX \"jobs_business_status_idx\" ON \"jobs\" USING btree (\"business_id\",\"status\");",
      "CREATE INDEX \"jobs_scheduled_idx\" ON \"jobs\" USING btree (\"business_id\",\"scheduled_start\");",
      "CREATE INDEX \"leads_business_status_idx\" ON \"leads\" USING btree (\"business_id\",\"status\");",
      "CREATE INDEX \"messages_customer_idx\" ON \"messages\" USING btree (\"customer_id\");",
      "CREATE INDEX \"messages_business_idx\" ON \"messages\" USING btree (\"business_id\");",
      "CREATE INDEX \"payments_invoice_idx\" ON \"payments\" USING btree (\"invoice_id\");",
      "CREATE INDEX \"quote_items_quote_idx\" ON \"quote_items\" USING btree (\"quote_id\");",
      "CREATE UNIQUE INDEX \"quotes_token_idx\" ON \"quotes\" USING btree (\"public_token\");",
      "CREATE UNIQUE INDEX \"quotes_number_idx\" ON \"quotes\" USING btree (\"business_id\",\"number\");",
      "CREATE INDEX \"quotes_business_status_idx\" ON \"quotes\" USING btree (\"business_id\",\"status\");",
      "CREATE UNIQUE INDEX \"reviews_token_idx\" ON \"reviews\" USING btree (\"public_token\");",
      "CREATE INDEX \"tasks_due_idx\" ON \"scheduled_tasks\" USING btree (\"status\",\"run_at\");",
      "CREATE INDEX \"tasks_entity_idx\" ON \"scheduled_tasks\" USING btree (\"entity_type\",\"entity_id\");",
      "CREATE INDEX \"services_business_idx\" ON \"services\" USING btree (\"business_id\");",
      "CREATE INDEX \"sessions_user_idx\" ON \"sessions\" USING btree (\"user_id\");",
      "CREATE UNIQUE INDEX \"users_email_idx\" ON \"users\" USING btree (\"email\");",
      "CREATE INDEX \"users_business_idx\" ON \"users\" USING btree (\"business_id\");"
    ]
  }
];
