/** Realistic seed content for a Pacific Northwest landscaping company. */

export const SERVICES = [
  { key: "maintenance", name: "Lawn Maintenance", description: "Recurring mow, edge, blow and trim.", basePriceCents: 0, typicalHours: 1.2, minPriceCents: 6500, recurring: true, low: 90, high: 115 },
  { key: "cleanup", name: "Yard Cleanup", description: "Overgrowth removal, debris haul-off, bed reset.", basePriceCents: 9000, typicalHours: 4.5, minPriceCents: 35000, recurring: false, low: 82, high: 128 },
  { key: "mulch", name: "Mulch Installation", description: "Bed prep, edging and fresh bark or mulch.", basePriceCents: 18000, typicalHours: 3, minPriceCents: 32000, recurring: false, low: 85, high: 122 },
  { key: "tree", name: "Tree & Shrub Pruning", description: "Structural pruning, hedge shaping, deadwood removal.", basePriceCents: 6000, typicalHours: 3.5, minPriceCents: 28000, recurring: false, low: 85, high: 125 },
  { key: "sod", name: "Sod Installation", description: "Grade, amend soil and lay new turf.", basePriceCents: 62000, typicalHours: 7, minPriceCents: 95000, recurring: false, low: 88, high: 120 },
  { key: "irrigation", name: "Irrigation Repair", description: "Diagnose zones, replace heads and valves, tune coverage.", basePriceCents: 12000, typicalHours: 2.5, minPriceCents: 22000, recurring: false, low: 80, high: 135 },
  { key: "design", name: "Landscape Design & Planting", description: "Planting plan, plant sourcing and installation.", basePriceCents: 145000, typicalHours: 12, minPriceCents: 250000, recurring: false, low: 85, high: 130 },
  { key: "hardscape", name: "Paver Patio & Walkway", description: "Excavation, base, and paver or flagstone installation.", basePriceCents: 320000, typicalHours: 24, minPriceCents: 480000, recurring: false, low: 88, high: 125 },
  { key: "sodcare", name: "Aeration & Overseeding", description: "Core aeration, overseed and starter fertilizer.", basePriceCents: 8000, typicalHours: 2, minPriceCents: 19000, recurring: false, low: 90, high: 115 },
  { key: "leaves", name: "Leaf Removal", description: "Full property leaf clearing and disposal.", basePriceCents: 5000, typicalHours: 3, minPriceCents: 24000, recurring: false, low: 85, high: 125 },
];

export const CUSTOMERS = [
  { name: "Sarah Miller", street: "14207 NE 78th Pl", city: "Redmond", zip: "98052", lat: 47.6841, lng: -122.1215 },
  { name: "David & Karen Chen", street: "6120 149th Ave NE", city: "Redmond", zip: "98052", lat: 47.6712, lng: -122.1391 },
  { name: "Thomas Reyes", street: "2841 168th Ave SE", city: "Bellevue", zip: "98008", lat: 47.5891, lng: -122.1082 },
  { name: "Priya Raghavan", street: "4419 Somerset Blvd SE", city: "Bellevue", zip: "98006", lat: 47.5522, lng: -122.1601 },
  { name: "Mark Whitaker", street: "22315 SE 34th St", city: "Sammamish", zip: "98075", lat: 47.5798, lng: -122.0361 },
  { name: "Jennifer Okonkwo", street: "1832 NW Juanita Dr", city: "Kirkland", zip: "98034", lat: 47.7093, lng: -122.2072 },
  { name: "Robert Langley", street: "705 Front St N", city: "Issaquah", zip: "98027", lat: 47.5412, lng: -122.0331 },
  { name: "Amanda Foster", street: "9312 NE 132nd St", city: "Kirkland", zip: "98034", lat: 47.7241, lng: -122.1892 },
  { name: "Hector Salas", street: "3388 W Lake Sammamish Pkwy SE", city: "Bellevue", zip: "98008", lat: 47.5731, lng: -122.0941 },
  { name: "Lisa Hartmann", street: "17622 NE 40th Ct", city: "Redmond", zip: "98052", lat: 47.6402, lng: -122.1022 },
  { name: "Greg Nakamura", street: "5140 119th Ave SE", city: "Bellevue", zip: "98006", lat: 47.5621, lng: -122.1712 },
  { name: "Denise Whitfield", street: "12840 SE 43rd Pl", city: "Bellevue", zip: "98006", lat: 47.5582, lng: -122.1541 },
  { name: "Aaron Petrov", street: "24115 SE Issaquah Fall City Rd", city: "Issaquah", zip: "98029", lat: 47.5521, lng: -122.0142 },
  { name: "Michelle Arroyo", street: "8809 161st Ave NE", city: "Redmond", zip: "98052", lat: 47.6891, lng: -122.1102 },
  { name: "Kyle Brennan", street: "1420 228th Ave NE", city: "Sammamish", zip: "98074", lat: 47.6212, lng: -122.0331 },
  { name: "Yuki Tanaka", street: "3011 108th Ave NE", city: "Bellevue", zip: "98004", lat: 47.6402, lng: -122.1951 },
  { name: "Frank DiMarco", street: "18740 NE 95th St", city: "Redmond", zip: "98052", lat: 47.6982, lng: -122.0931 },
  { name: "Carol Bishop", street: "7211 122nd Ave NE", city: "Kirkland", zip: "98033", lat: 47.6731, lng: -122.1741 },
  { name: "Nathan Osei", street: "5602 138th Ave SE", city: "Bellevue", zip: "98006", lat: 47.5501, lng: -122.1482 },
  { name: "Rebecca Lindqvist", street: "20819 NE 12th St", city: "Sammamish", zip: "98074", lat: 47.6121, lng: -122.0512 },
  { name: "Omar Haddad", street: "1115 Newport Way NW", city: "Issaquah", zip: "98027", lat: 47.5361, lng: -122.0471 },
  { name: "Patricia Vaughn", street: "10420 NE 60th St", city: "Kirkland", zip: "98033", lat: 47.6641, lng: -122.1892 },
  { name: "Daniel Kowalski", street: "16302 SE 6th St", city: "Bellevue", zip: "98008", lat: 47.6081, lng: -122.1201 },
  { name: "Grace Mwangi", street: "4507 244th Ave SE", city: "Sammamish", zip: "98029", lat: 47.5691, lng: -122.0182 },
  { name: "Steven Ashford", street: "13311 NE 175th St", city: "Woodinville", zip: "98072", lat: 47.7541, lng: -122.1541 },
];

export const CREW_MEMBERS = [
  { name: "Mike Alvarez", role: "owner" as const, email: "mike@cascadegreen.com", color: "#2a6746" },
  { name: "Dana Whitcomb", role: "admin" as const, email: "dana@cascadegreen.com", color: "#a5371e" },
  { name: "Luis Ortega", role: "crew" as const, email: "luis@cascadegreen.com", color: "#3a8059" },
  { name: "Tyler Brooks", role: "crew" as const, email: "tyler@cascadegreen.com", color: "#c74a22" },
  { name: "Andre Cole", role: "crew" as const, email: "andre@cascadegreen.com", color: "#585245" },
  { name: "Marcus Webb", role: "crew" as const, email: "marcus@cascadegreen.com", color: "#22523a" },
  { name: "Jesse Ruiz", role: "crew" as const, email: "jesse@cascadegreen.com", color: "#8a8376" },
  { name: "Cody Nguyen", role: "crew" as const, email: "cody@cascadegreen.com", color: "#d9612c" },
];

/** Real-sounding inbound requests, in the register customers actually write in. */
export const LEAD_REQUESTS = [
  { text: "Hey, looking to get my backyard cleaned up and have some new mulch put down. Can someone come take a look?", service: "cleanup", source: "website" },
  { text: "Our sprinkler system has a zone that isn't coming on at all and another that's flooding the sidewalk. Need someone out this week if possible.", service: "irrigation", source: "google" },
  { text: "Need weekly mowing for a corner lot in Redmond. About a quarter acre. What do you charge?", service: "maintenance", source: "referral" },
  { text: "We're listing the house next month and the front yard looks rough. Want to get it looking sharp before photos.", service: "cleanup", source: "facebook" },
  { text: "Looking for a quote on a paver patio, roughly 20x16, off the back slider.", service: "hardscape", source: "website" },
  { text: "The laurel hedge along our fence has gotten way out of control. Probably 60 feet of it, needs to come down to a reasonable height.", service: "tree", source: "instagram" },
  { text: "Lawn is mostly moss at this point. Curious what it would cost to tear it out and put in new sod.", service: "sod", source: "website" },
  { text: "Can you do a one-time cleanup? Lots of blackberry and ivy along the back fence line.", service: "cleanup", source: "phone" },
  { text: "Need mulch in the front beds, about 8 yards worth I think. Also could use the beds edged.", service: "mulch", source: "repeat" },
  { text: "Interested in a full landscape redesign for the front yard. Want something low maintenance and drought tolerant.", service: "design", source: "website" },
  { text: "Leaves are completely covering the yard and the gutters are packed. Need it cleared before the rain really starts.", service: "leaves", source: "text" },
  { text: "HOA sent us a violation notice about the yard. Need it handled ASAP, whatever it takes.", service: "cleanup", source: "phone" },
  { text: "Would like to get on a regular maintenance schedule starting in spring. Half acre property in Sammamish.", service: "maintenance", source: "referral" },
  { text: "Two big rhododendrons need pruning and there's a dead branch over the driveway I'm worried about.", service: "tree", source: "website" },
  { text: "We're hosting a graduation party in three weeks and the yard needs serious help.", service: "cleanup", source: "facebook" },
  { text: "Aeration and overseeding quote please. Lawn is about 4000 sq ft.", service: "sodcare", source: "google" },
  { text: "Irrigation backflow test is due and I think we have a leak near the meter.", service: "irrigation", source: "email" },
  { text: "New construction, bare dirt lot. Need the whole thing landscaped — lawn, beds, the works.", service: "design", source: "referral" },
  { text: "Just bought the house and the previous owners let everything go. Where do we even start?", service: "cleanup", source: "website" },
  { text: "Walkway from the driveway to the front door is cracked and uneven. Looking at flagstone maybe?", service: "hardscape", source: "website" },
  { text: "Need someone reliable for biweekly mowing May through September.", service: "maintenance", source: "walk_by" },
  { text: "Can I get a price on mulch delivery and spread? Dark brown, about 10 yards.", service: "mulch", source: "text" },
  { text: "Getting quotes from a few companies for a backyard overhaul. Budget is flexible for the right plan.", service: "design", source: "google" },
  { text: "The strip between the sidewalk and street is all weeds. Want something that looks intentional.", service: "design", source: "instagram" },
  { text: "Storm knocked down a big limb in the back. Need it cut up and hauled out.", service: "tree", source: "phone" },
  { text: "Looking for fall cleanup — leaves, cutting back perennials, and a mulch top dress.", service: "leaves", source: "repeat" },
  { text: "My sprinkler heads are spraying the house instead of the lawn. Also the timer seems dead.", service: "irrigation", source: "website" },
  { text: "Side yard is a mud pit. Thinking gravel or pavers, open to suggestions.", service: "hardscape", source: "referral" },
  { text: "Need a quote for monthly maintenance on a rental property I manage in Kirkland.", service: "maintenance", source: "email" },
  { text: "Front lawn has big bare patches from the dog. Can that be patched or does it all need replacing?", service: "sod", source: "website" },
  { text: "Want to get rid of the lawn entirely and put in native plants and gravel paths.", service: "design", source: "instagram" },
  { text: "Hedges need trimming and the beds need weeding. Pretty standard tune-up.", service: "tree", source: "repeat" },
  { text: "Bark is looking faded and thin everywhere. Time for a refresh on about 1200 sq ft of beds.", service: "mulch", source: "repeat" },
  { text: "We just want the yard mowed every two weeks and nothing else. Keep it simple.", service: "maintenance", source: "walk_by" },
  { text: "Retaining wall in the back is bowing out. Not sure if that's something you handle.", service: "hardscape", source: "phone" },
  { text: "Overgrown everything. Been neglected two years. Need an estimate for getting it back under control.", service: "cleanup", source: "website" },
  { text: "Can you install sod in October or should we wait until spring?", service: "sod", source: "email" },
  { text: "Sprinkler system needs winterizing and I'd like it on a recurring schedule.", service: "irrigation", source: "repeat" },
  { text: "Small front yard, just needs the beds cleaned out and fresh mulch. Should be quick.", service: "mulch", source: "google" },
  { text: "Interested in seasonal color — planters and bed annuals, refreshed a few times a year.", service: "design", source: "referral" },
];

export const CREWS = [
  { name: "Crew A", color: "#2a6746" },
  { name: "Crew B", color: "#c74a22" },
  { name: "Crew C", color: "#585245" },
];

export const JOB_CHECKLIST = ["Arrived on site", "Work started", "Materials delivered", "Work completed", "Photos uploaded", "Customer walkthrough"];
